In [20]:
import pandas as pd

# Loading dataset

In [21]:
df = pd.read_csv("./datasets/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Describing the dataset

In [22]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# Null Count

In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# preprocessing null data

In [24]:
df["Age"] = df["Age"].fillna(df["Age"].median()) # median due to high variance

In [25]:
df = df.drop("Cabin", axis=1) # majority data missing

In [34]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [35]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

# normalisation

In [36]:
min_max_normilizer = lambda x : (x - x.min())/(x.max() - x.min())

In [37]:
df[["Age", "Fare"]] = df[["Age", "Fare"]].apply(min_max_normilizer)

In [38]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,S
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,S
5,6,0,3,"Moran, Mr. James",male,0.346569,0,0,330877,0.016510,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,0.673285,0,0,17463,0.101229,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,0.019854,3,1,349909,0.041136,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,0.334004,0,2,347742,0.021731,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,0.170646,1,0,237736,0.058694,C

# Results

In [40]:
columns = df.select_dtypes(include="number").columns
columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='str')

In [42]:
print("Range:")
df[columns].max() - df[columns].min()

Range:

PassengerId    890.0
Survived         1.0
Pclass           2.0
Age              1.0
SibSp            8.0
Parch            6.0
Fare             1.0
dtype: float64

In [44]:
print("Variance:")
df[columns].var()

Variance:

PassengerId    66231.000000
Survived           0.236772
Pclass             0.699015
Age                0.026767
SibSp              1.216043
Parch              0.649728
Fare               0.009408
dtype: float64

In [48]:
df[columns].quantile([0.25, 0.50, 0.75])

      PassengerId  Survived  Pclass       Age  SibSp  Parch      Fare
0.25        223.5       0.0     2.0  0.271174    0.0    0.0  0.015440
0.50        446.0       0.0     3.0  0.346569    0.0    0.0  0.028213
0.75        668.5       1.0     3.0  0.434531    1.0    0.0  0.060508

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,S
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,S